/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tepach.fmc;

import java.awt.FileDialog;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Stack;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.ir.BreakNode;

/**
 *
 * @author Anthony Tepach
 */
public class Apps extends javax.swing.JFrame {

    /**
     * Creates new form Apps
     */
    private ArrayList<String> hola = new ArrayList();
    private Stack<String> pila = new Stack<String>();
    private Stack<String> pila_dos = new Stack<String>();
    private int contador = 0;

    public Apps() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtff_ini = new javax.swing.JTextField();
        jtf_fin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1_folios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Folio Inicial");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Folio Final");

        jtff_ini.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtff_ini.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtff_iniKeyTyped(evt);
            }
        });

        jtf_fin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtf_fin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_finKeyTyped(evt);
            }
        });

        jButton1.setText("Generar BD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1_folios.setText("Folios generados: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jtff_ini, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1_folios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtff_ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jLabel1_folios)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!this.jtff_ini.getText().isEmpty() && !this.jtf_fin.getText().isEmpty()) {
            int folini = Integer.parseInt(this.jtff_ini.getText());
            int folfin = Integer.parseInt(this.jtf_fin.getText());
            if (folini > folfin) {
                JOptionPane.showMessageDialog(this.rootPane, "El folio inicial no debe ser mayor al folio final.", "Error", 0);
            } else if (folfin - folini == 1000000) {
                generarDV(folini, folfin);
                
            } else {
                JOptionPane.showMessageDialog(this.rootPane, "Solo puedes crear bases de 1,000,000 de folios");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtff_iniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtff_iniKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtff_iniKeyTyped

    private void jtf_finKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_finKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_finKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apps().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1_folios;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtf_fin;
    private javax.swing.JTextField jtff_ini;
    // End of variables declaration//GEN-END:variables

    private void generarDV(int folini, int folfin) {
        int sumas = 0;
        int p = 0;
        int resta = folfin - folini;
        int i;
        for (i = 0; i < 10000; i++) {
            this.pila.push("00000000" + letrasAl().toUpperCase() + Character.MIN_VALUE);
            //this.hola.add("00000000" + letrasAl().toUpperCase() + Character.MIN_VALUE);
        }
        for (i = folini; i < folfin; i++) {
            String smu =String.format("%08d",(i+1));
           // System.out.println(smu);
            int[] asuma = new int[smu.length()];
            int nums = Integer.parseInt(smu);
            for (int j = 0; j < smu.length(); j++) {
                int num = j + 1;
                sumas = Integer.parseInt(smu.substring(j, num));
                int mult = 0;
                mult = sumas * num;
                int cont = 0;
                asuma[j] = mult;
                int total = 0;
                for (int k = 0; k < asuma.length; k++) {
                    total += asuma[k];
                }
                if (j == smu.length() - 1) {
                    this.pila.push(smu + letrasAl().toUpperCase() + DV(Integer.parseInt(resuido(total))));
                    this.hola.add(smu + letrasAl().toUpperCase() + DV(Integer.parseInt(resuido(total))));
                }
            }
        }
        this.pila_dos.addAll(this.pila);
        generartxt(pila_dos, new FileBrowser().guardarComo());
        this.jLabel1_folios.setText("Folios creados: " + this.pila.size());
        String rute = getRuta();
        File salida = new File(rute);
        String archivo = salida.getName();
        String carpeta = salida.getParent();
        
         
       
        
        //GenerarArchivos(this.pila, archivo, carpeta);
        GenerarArchivos(hola, archivo, carpeta);
    }

    private void GenerarArchivos(Stack<String> pila, String archivo, String carpeta) {
         
        if (pila.size() < 70000) {
            if (!pila.empty()) {
                int particion = pila.size() / 10;
                String[][] matriz = new String[particion][10];
                int f;
                for (f = 0; f < matriz.length; f++) {
                    for (int i = 0; i < 10; i++) {
                         matriz[f][i] = pila.pop();
                    }
                }
               
                crearArchivosVarios(pila, matriz, archivo, carpeta);
            } else {
                JOptionPane.showMessageDialog(this.rootPane, "Se guardo en: \n" + carpeta, "Saliendo", 1);
                System.exit(0);
            }
        } else {
            String[][] matriz = new String[10000][10];
            int f;
            for (f = 0; f < matriz.length; f++) {
                    for (int i = 0; i < 10; i++) {
                         matriz[f][i] = pila.pop();
                    }
                }
            crearArchivosVarios(pila, matriz, archivo, carpeta);
        }
    }
 private void GenerarArchivos(ArrayList<String> lista, String archivo, String carpeta) {
         
        if (lista.size() < 70000) {
            if (!lista.isEmpty()) {
                int particion = lista.size() / 10;
                String[][] matriz = new String[particion][10];
                int f;
                for (f = 0; f < matriz.length; f++) {
                    for (int i = 0; i < 10; i++) {
                         matriz[f][i] = lista.get(f);
                    }
                }
               
                crearArchivosVarios(lista, matriz, archivo, carpeta);
            } else {
                JOptionPane.showMessageDialog(this.rootPane, "Se guardo en: \n" + carpeta, "Saliendo", 1);
                System.exit(0);
            }
        } else {
            String[][] matriz = new String[10000][10];
            int f;
            for (f = 0; f < matriz.length; f++) {
                    for (int i = 0; i < 10; i++) {
                         matriz[f][i] =lista.get(f);
                    }
                }
            crearArchivosVarios(lista, matriz, archivo, carpeta);
        }
    }
    private void crearArchivosVarios(Stack<String> pila, String[][] matriz, String archivo, String carpeta) {
        this.contador++;
        FileWriter fichero = null;
        PrintWriter pw = null;
        try {
            if (!archivo.contains(".txt")) {
                archivo = archivo.concat(".txt");
            }
            fichero = new FileWriter(carpeta + "/" + this.contador + " particion-" + archivo);
            pw = new PrintWriter(fichero);
            for (int f = 0; f < matriz.length; f++) {
                for (int c = 0; c < (matriz[f]).length; c++) {
                    pw.print(matriz[f][c] + "\t");
                }
                pw.println();
            }
            pw.close();
            fichero.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        GenerarArchivos(pila, archivo, carpeta);
    }
    
    private void crearArchivosVarios(ArrayList<String> lista, String[][] matriz, String archivo, String carpeta) {
        this.contador++;
        FileWriter fichero = null;
        PrintWriter pw = null;
        try {
            if (!archivo.contains(".txt")) {
                archivo = archivo.concat(".txt");
            }
            fichero = new FileWriter(carpeta + "/" + this.contador + " particion-" + archivo);
            pw = new PrintWriter(fichero);
            for (int f = 0; f < matriz.length; f++) {
                for (int c = 0; c < (matriz[f]).length; c++) {
                    pw.print(matriz[f][c] + "\t");
                }
                pw.println();
            }
            pw.close();
            fichero.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        GenerarArchivos(lista, archivo, carpeta);
    }

    private String resuido(int cont) {
        return String.valueOf(cont % 11);
    }

    private String letrasAl() {
        int num1 = 97;
        int num2 = 122;
        char c = 0;
        int numAleatorio = (int) Math.floor(Math.random() * (num2 - num1) + num1);
        return "" + (char) numAleatorio;
    }

    private int DV(int resuido) {
        int dv;
        if (String.valueOf(resuido).length() > 1) {
            dv = Integer.parseInt(String.valueOf(resuido).substring(0, 1));
        } else {
            dv = resuido;
        }
        return dv;
    }

    private String getRuta() {
        String ruta = null;
        FileDialog dialogoArchivo;
        dialogoArchivo = new FileDialog(this, "Guardar como...", FileDialog.SAVE);
        dialogoArchivo.setVisible(true);
        ruta = dialogoArchivo.getDirectory() + dialogoArchivo.getFile();
        return ruta;
    }

    private void generartxt(Stack<String> pila, String ruta) {
        if (ruta == null || ruta == "") {
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar una ruta", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            FileWriter fichero = null;
            PrintWriter pw = null;
            try {
                if (!ruta.contains(".txt")) {
                    ruta = ruta.concat(".txt");
                }
                fichero = new FileWriter(ruta);
                pw = new PrintWriter(fichero);
                while (!pila.empty()) {
                    pw.println(pila.pop().substring(8,10));
                }
                pw.close();
                fichero.close();
                JOptionPane.showMessageDialog(rootPane, "Se guardando en: \n" + ruta, "Exito", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }
}
