/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tepach.fmc;

import java.awt.FileDialog;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Stack;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.ir.BreakNode;

/**
 *
 * @author Anthony Tepach
 */
public class Apps extends javax.swing.JFrame {

    /**
     * Creates new form Apps
     */
    ArrayList<String> hola = new ArrayList();
    Stack<String> pila = new Stack<String>();

    public Apps() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtff_ini = new javax.swing.JTextField();
        jtf_fin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1_folios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Folio Inicial");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Folio Final");

        jtff_ini.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtff_ini.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtff_iniKeyTyped(evt);
            }
        });

        jtf_fin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtf_fin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_finKeyTyped(evt);
            }
        });

        jButton1.setText("Generar BD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1_folios.setText("Folios generados: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jtff_ini, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1_folios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtff_ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jLabel1_folios)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
    
        if (!jtff_ini.getText().isEmpty() && !jtf_fin.getText().isEmpty()) {
            int folini = Integer.parseInt(jtff_ini.getText());
            int folfin = Integer.parseInt(jtf_fin.getText());
            if (folini > folfin) {
                JOptionPane.showMessageDialog(rootPane, "El folio inicial no debe ser mayor al folio final.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                generarDV(folini, folfin);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtff_iniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtff_iniKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtff_iniKeyTyped

    private void jtf_finKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_finKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_finKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apps().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1_folios;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtf_fin;
    private javax.swing.JTextField jtff_ini;
    // End of variables declaration//GEN-END:variables

    private void generarDV(int folini, int folfin) {

        int sumas = 0, resuido, num, p = 0;
        for (int i = folini; i < folfin; i++) {

            String smu = String.valueOf((i + 1));
            int[] asuma = new int[smu.length()];
            int nums = Integer.parseInt(smu);
            for (int j = 0; j < smu.length(); j++) {
                num = j + 1;
                sumas = Integer.parseInt(smu.substring(j, num));
                int mult = 0;
                mult = sumas * num;
                int cont = 0;

                asuma[j] = mult;
                int total = 0;
                //System.out.println(sumas + " * " + num + " = " + mult);
                for (int k = 0; k < asuma.length; k++) {
                    total = total + asuma[k];
                    //System.out.println(total);
                }
                if (j == smu.length() - 1) {
                    //System.out.println("Suma total: " + total + "\nResuido: " + resuido(total) + "\nletra: " + letrasAl().toUpperCase() + "\nfolio: " + smu+"\nDV: "+DV(Integer.parseInt(resuido(total))));
                    pila.push(smu + letrasAl().toUpperCase() + DV(Integer.parseInt(resuido(total))));

                }

            }
        }
        jLabel1_folios.setText("Folios creados: " + pila.size());
        generartxt(pila, getRuta());
    }

    private String resuido(int cont) {
        return String.valueOf(cont % 11);
    }

    private String letrasAl() {
        int num1 = 97;
        int num2 = 122;
        char c = 0;
        int numAleatorio = (int) Math.floor(Math.random() * (num2 - num1) + num1);
        return "" + (char) numAleatorio;
    }

    private int DV(int resuido) {
        int dv;
        if (String.valueOf(resuido).length() > 1) {
            dv = Integer.parseInt(String.valueOf(resuido).substring(0, 1));
        } else {
            dv = resuido;
        }
        return dv;
    }

    private String getRuta() {
        String ruta = null;
        FileDialog dialogoArchivo;
        dialogoArchivo = new FileDialog(this, "Guardar como...", FileDialog.SAVE);
        dialogoArchivo.setVisible(true);
        ruta = dialogoArchivo.getDirectory() + dialogoArchivo.getFile();
        return ruta;
    }

    private void generartxt(Stack<String> pila, String ruta) {
        if (ruta == null || ruta =="" ) {
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar una ruta", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            FileWriter fichero = null;
            PrintWriter pw = null;
            try {
                if (!ruta.contains(".txt")) {
                    ruta = ruta.concat(".txt");
                }
                fichero = new FileWriter(ruta);
                pw = new PrintWriter(fichero);
                while (!pila.empty()) {
                    pw.println(pila.pop());
                }
                pw.close();
                fichero.close();
                JOptionPane.showMessageDialog(rootPane, "Se guardando en: \n" + ruta, "Exito", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }
}
